#!/bin/bash

# Update Thu, 24 Nov 2022 12:25:29 +0900 by Kevin Kim

DEVCHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

# set 755 chmod to / (root dir)
chmod 755 $DEVCHROOT

CHECKGRUB=`cat $DEVCHROOT/etc/default/grub | grep "GRUB_ENABLE_CRYPTODISK"`
if [ "$CHECKGRUB" = " " ] && [ -f "$DEVCHROOT/crypto*" ]; then
	echo "GRUB_ENABLE_CRYPTODISK=y" >> $DEVCHROOT/etc/default/grub
fi

# copy skel to home
TARGETUSER=`cat $DEVCHROOT/etc/passwd | grep 1000 | awk -F ":" '{print $1}'`
cd /etc/skel
if [ ! -d $DEVCHROOT/home/$TARGETUSER ]; then
	mkdir -p $DEVCHROOT/home/$TARGETUSER
fi
rsync -ar . $DEVCHROOT/home/$TARGETUSER

# update user conut
cat > $DEVCHROOT/tmp/fixcrypto << FOO
#!/bin/bash
chown -R $TARGETUSER:$TARGETUSER /home/$TARGETUSER
if [ ! -f /crypto* ]; then
	apt-get purge cryptsetup* --yes
fi
FOO

chmod +x $DEVCHROOT/tmp/fixcrypto
chroot $DEVCHROOT /tmp/fixcrypto
rm -f $DEVCHROOT/tmp/fixcrypto

# update user conut
cat > $DEVCHROOT/tmp/hamonikrrun << FOO
#!/bin/bash
chown -R $TARGETUSER:$TARGETUSER /home/$TARGETUSER

log() {
    # stdout
    echo "$@"
    # write to logfile
    [ ! -f /var/log/hamonikr-postint.log ] && sudo touch /var/log/hamonikr-postint.log
    chmod 666 /var/log/hamonikr-postint.log
    exec 3>&1 1>>/var/log/hamonikr-postint.log 2>&1 && echo "$(date +%Y-%m-%d_%H:%M_%S) ${0##*/} : $@"
    # stdout reset
    exec 1>&3 3>&-
}

if [ -f /etc/ufw/ufw.conf ]; then
    sed -i 's/ENABLED=no/ENABLED=yes/g' /etc/ufw/ufw.conf
    if [ $? -eq 0 ] ; then
        log "Update Firewall Settings..."
    fi
fi

if [ -f /etc/passwd ]; then
    grep "$TARGETUSER" /etc/passwd | sed -i 's|/bin/bash|/usr/bin/zsh|g' /etc/passwd
    if [ $? -eq 0 ] ; then
        log "Update default user shell to zsh..."
    fi
fi

if [ -f /etc/hamonikr/adjustments/10-adjust-grub-title.execute ]; then
    /etc/hamonikr/adjustments/10-adjust-grub-title.execute
    if [ $? -eq 0 ] ; then
        log "Update grub title..."
    else
        log "Could not change grub title"
    fi
fi

cat /dev/null | sudo tee /etc/machine-id

if [ -f "/etc/hamonikr/info" ] ; then
    RD=`head -c 16 /dev/urandom | md5sum | head -c 32`
    source /etc/hamonikr/info
    if [ -z $CODENAME ] ; then
        CODENAME="Unknown"
    else
        CODENAME="$CODENAME"
    fi
    if [ -z $RELEASE ] ; then
        RELEASE = "Unknown"
    fi
    if ping -q -c 1 -W 1 u.hamonikr.org >/dev/null; then
        curl -XPOST "http://u.hamonikr.org:8086/write?db=hamonikr" --data-binary "machineid,codename=$CODENAME,version=$RELEASE value=\"$RD\""
        log "Update installed log..."
    fi
fi

FOO

chmod +x $DEVCHROOT/tmp/hamonikrrun
chroot $DEVCHROOT /tmp/hamonikrrun
rm -f $DEVCHROOT/tmp/hamonikrrun
